/**
 * VelChat local dev API gateway.
 *
 * Fronts all services on ONE port so a client hits http://localhost:8080 and requests are
 * proxied to the right service by path prefix (e.g. /auth → auth-service, /chat → chat-service).
 * WebSocket upgrades route to realtime-gateway. Routes come from tools/gateway/services.json
 * (regenerated by the scaffolder), so this stays in sync automatically.
 *
 *   node tools/gateway/dev-gateway.mjs        # or: pnpm gateway
 */
import http from 'node:http';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import httpProxy from 'http-proxy';

const here = dirname(fileURLToPath(import.meta.url));
const services = JSON.parse(readFileSync(join(here, 'services.json'), 'utf8'));
const PORT = Number(process.env.GATEWAY_PORT ?? 8080);

const routeTable = [];
let defaultTarget = null;
for (const s of services) {
  const target = `http://localhost:${s.http}`;
  if (s.name === 'api-gateway') defaultTarget = target;
  for (const prefix of s.routes) routeTable.push({ prefix, target, ws: s.ws, name: s.name });
}
routeTable.sort((a, b) => b.prefix.length - a.prefix.length); // longest prefix wins

function match(url) {
  for (const r of routeTable) {
    if (url === r.prefix || url.startsWith(`${r.prefix}/`) || url.startsWith(`${r.prefix}?`)) return r;
  }
  return defaultTarget ? { prefix: '/', target: defaultTarget, ws: false, name: 'api-gateway' } : null;
}

const proxy = httpProxy.createProxyServer({ changeOrigin: true, ws: true });
proxy.on('error', (err, req, res) => {
  if (res && typeof res.writeHead === 'function' && !res.headersSent) {
    res.writeHead(502, { 'Content-Type': 'application/json' });
    res.end(
      JSON.stringify({
        error: 'Bad Gateway',
        message: 'Target service not reachable — is it running?',
        path: req.url,
      }),
    );
  }
});

const server = http.createServer((req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,PUT,PATCH,DELETE,OPTIONS');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'Content-Type, Authorization, Accept, x-tenant-id, x-account-id, x-trace-id',
  );
  if (req.method === 'OPTIONS') {
    res.writeHead(204);
    res.end();
    return;
  }
  if (req.url === '/health' || req.url === '/') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ status: 'ok', gateway: 'velchat-dev', routes: routeTable.length }));
    return;
  }
  const r = match(req.url);
  if (!r) {
    res.writeHead(404, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Not Found', message: 'No service route matched', path: req.url }));
    return;
  }
  console.log(`${req.method} ${req.url} → ${r.name} (${r.target})`);
  proxy.web(req, res, { target: r.target });
});

server.on('upgrade', (req, socket, head) => {
  const r = match(req.url);
  const target = r && r.ws ? r.target : routeTable.find((x) => x.ws)?.target;
  if (!target) {
    socket.destroy();
    return;
  }
  proxy.ws(req, socket, head, { target });
});

server.listen(PORT, () => {
  console.log(`\n  VelChat dev gateway → http://localhost:${PORT}\n`);
  for (const r of routeTable) console.log(`   ${r.prefix.padEnd(16)} → ${r.target}  (${r.name})`);
  console.log(`   ${'(default)'.padEnd(16)} → ${defaultTarget}  (api-gateway)`);
  console.log('\n  Make sure the services are running (pnpm start:all). Ctrl+C to stop.\n');
});

process.on('SIGINT', () => server.close(() => process.exit(0)));
process.on('SIGTERM', () => server.close(() => process.exit(0)));
